"""initial schema

Revision ID: 0b94242b3368
Revises: 
Create Date: 2026-04-02 18:30:03.360557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b94242b3368'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_slug'), 'domains', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('supabase_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('tier', sa.Enum('REGISTERED', 'PARTICIPANT', 'FACILITATOR', 'ADMIN', name='user_tier'), nullable=False),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('event_type', sa.Enum('USER_REGISTERED', 'USER_TIER_CHANGED', 'USER_DEACTIVATED', 'THREAD_CREATED', 'THREAD_PHASE_ADVANCED', 'POST_CREATED', 'POST_REMOVED', 'SIGNAL_CAST', 'SIGNAL_UPDATED', 'PROPOSAL_CREATED', 'PROPOSAL_SUBMITTED', 'PROPOSAL_STATUS_CHANGED', 'VOTE_CAST', 'ALLOCATION_DECIDED', 'LLM_SUMMARY_GENERATED', name='audit_event_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('funding_pools',
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('allocated_amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('pool_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pool_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_pools_domain_id'), 'funding_pools', ['domain_id'], unique=False)
    op.create_table('threads',
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DELIBERATING', 'PROPOSING', 'VOTING', 'CLOSED', 'ARCHIVED', name='thread_status'), nullable=False),
    sa.Column('phase_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_domain_id'), 'threads', ['domain_id'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('removal_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_thread_id'), 'posts', ['thread_id'], unique=False)
    op.create_table('proposals',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'VOTING', 'PASSED', 'REJECTED', 'IMPLEMENTED', name='proposal_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_thread_id'), 'proposals', ['thread_id'], unique=False)
    op.create_table('signals',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('SUPPORT', 'CONCERN', 'NEED_INFO', 'BLOCK', name='signal_type'), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_signal_thread_user')
    )
    op.create_index(op.f('ix_signals_thread_id'), 'signals', ['thread_id'], unique=False)
    op.create_table('allocation_decisions',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('vote_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['funding_pools.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_table('votes',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('choice', sa.Enum('YES', 'NO', 'ABSTAIN', name='vote_choice'), nullable=False),
    sa.Column('rationale', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_id', name='uq_vote_proposal_voter')
    )
    op.create_index(op.f('ix_votes_proposal_id'), 'votes', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_proposal_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('allocation_decisions')
    op.drop_index(op.f('ix_signals_thread_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_proposals_thread_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_posts_thread_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_domain_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_funding_pools_domain_id'), table_name='funding_pools')
    op.drop_table('funding_pools')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_domains_slug'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
